import {mountAWOS} from './awos.js';
const nrc='https://www.nrc.gov/about-nrc/radiation/protects-you/protection-principles';
const cdc='https://www.cdc.gov/infection-control/hcp/disinfection-sterilization/chemical-disinfectants.html';
const field=(key,label,value,unit='')=>({key,label:label+(unit?' ('+unit+')':''),value});
export const calculators=[
{id:'wbgt',group:'Heat stress',title:'WBGT calculator',icon:'☀',description:'Calculate wet-bulb globe temperature from on-site sensor measurements.',fields:[field('wet','Natural wet-bulb',77.0,'°F'),field('globe','Globe temperature',95.0,'°F'),field('dry','Dry-bulb air temperature',89.6,'°F')],formula:'WBGT = 0.7 Tnwb + 0.2 Tg + 0.1 Tdb',notes:'Requires natural wet-bulb and globe measurements. An AWOS air temperature or dew point alone is not a measured WBGT. Clothing, workload and acclimatization are needed for work/rest decisions. Choose sensor readings or load a modeled estimate from an AWOS weather station. Weather-derived values are estimates, not direct sensor measurements.',source:'https://www.osha.gov/heat-exposure/hazards',calc:v=>[.7*v.wet+.2*v.globe+.1*v.dry,'°F WBGT','No clothing adjustment applied.']},
{id:'dose',group:'Radiation',title:'Radiation dose',icon:'☢',description:'Estimate accumulated dose from a constant measured dose rate and exposure time.',fields:[field('rate','Dose rate',10,'µSv/h'),field('time','Exposure time',30,'min')],formula:'Dose = dose rate × time / 60',notes:'Assumes a constant dose rate throughout exposure. Uses dose equivalent units; do not substitute exposure (R) or absorbed dose (Gy) without a justified conversion.',source:nrc,calc:v=>[v.rate*v.time/60,'µSv','Constant-rate dose estimate.']},
{id:'distance',group:'Radiation',title:'Inverse-square law',icon:'☢',description:'Estimate the dose rate at a different distance from a point source.',fields:[field('rate','Reference dose rate',100,'µSv/h'),field('r1','Reference distance',1,'m'),field('r2','New distance',2,'m')],positive:['r1','r2'],formula:'Rate₂ = Rate₁ × (distance₁ / distance₂)²',notes:'Applies to a point source in free space, without shielding, attenuation or significant scatter. Distances are measured from the source. This is the inverse-square law, not an inverse-square-root relationship.',source:nrc,calc:v=>[v.rate*(v.r1/v.r2)**2,'µSv/h','Estimated dose rate at the new distance.']},
{id:'stay',group:'Radiation',title:'Stay time',icon:'◷',description:'Calculate the time remaining within a user-defined dose budget.',fields:[field('budget','Total dose budget',100,'µSv'),field('used','Dose already received',20,'µSv'),field('rate','Dose rate',10,'µSv/h')],positive:['rate'],formula:'Time = max(0, budget − received) / rate',notes:'Enter a dose budget established by your radiation protection program. This is a mathematical budget estimate, not permission to enter or remain in a radiation area. Assumes a constant rate.',source:nrc,calc:v=>[Math.max(0,v.budget-v.used)/v.rate*60,'min',v.used>=v.budget?'Dose budget reached or exceeded.':'Based on the remaining '+fmt(v.budget-v.used)+' µSv budget.']},
{id:'hth',group:'Disinfection',title:'HTH chlorine solution',icon:'◈',description:'Calculate dry calcium hypochlorite needed to prepare a target chlorine solution.',fields:[field('volume','Final solution volume',100,'L'),field('target','Target available chlorine',50,'mg/L'),field('strength','Available chlorine by mass',65,'%')],positive:['volume','strength'],formula:'Product (g) = target (mg/L) × volume (L) / (10 × strength %)',notes:'Use the product’s labeled available chlorine percentage. Assumes zero starting chlorine and complete dissolution. Make up to the final volume; actual residual must be measured after the required contact time. Follow the label and local protocol. Never mix chlorine products with acids or ammonia.',source:cdc,calc:v=>[v.target*v.volume/(10*v.strength),'g HTH','Mass of product, not mass of pure chlorine.']},
{id:'liquid',group:'Disinfection',title:'Liquid chlorine dilution',icon:'◈',description:'Calculate liquid bleach needed for a chosen final concentration and volume.',fields:[field('volume','Final solution volume',10,'L'),field('target','Target available chlorine',1000,'mg/L'),field('stock','Stock available chlorine',60000,'mg/L')],positive:['volume','stock'],formula:'Stock (mL) = target / stock × final volume (L) × 1000',notes:'Enter available chlorine in mg/L from the label or supplier. 1% w/v available chlorine = 10,000 mg/L. Do not equate a sodium hypochlorite % w/w label to available chlorine % w/v; density and chlorine equivalence matter. Use an appropriate unscented product and follow its label. Never mix with acids or ammonia.',source:cdc,calc:v=>{if(v.target>v.stock)throw Error('Target concentration cannot exceed stock concentration.');const ml=v.target/v.stock*v.volume*1000;return[ml,'mL stock','Dilute with water to '+fmt(v.volume)+' L total (approximately '+fmt(v.volume-ml/1000)+' L water).'];}},
{id:'residual',group:'Disinfection',title:'Chlorine demand & residual',icon:'◈',description:'Calculate chlorine demand from an applied dose and a measured free residual.',fields:[field('dose','Applied chlorine dose',5,'mg/L'),field('residual','Measured free residual',1,'mg/L'),field('time','Contact time',30,'min')],formula:'Demand = dose − residual; CT = residual × time',notes:'Residual is a field measurement, not a guaranteed result of a dosing calculation. Demand depends on water quality and contact time. CT shown here assumes the entered residual is maintained for the entire period; it does not establish treatment efficacy or drinking-water safety.',source:cdc,calc:v=>{if(v.residual>v.dose)throw Error('Residual exceeds applied dose. Check the starting chlorine, measurements and units.');return[v.dose-v.residual,'mg/L demand','CT estimate: '+fmt(v.residual*v.time)+' mg·min/L.'];}},
];
export function calculate(id,values){const c=calculators.find(c=>c.id===id);if(!c)throw Error('Unknown calculator.');const v={};for(const f of c.fields){const raw=values[f.key];if(raw===undefined||raw===null||String(raw).trim()===''||!Number.isFinite(Number(raw)))throw Error('Enter a valid number for '+f.label+'.');v[f.key]=Number(raw);if(id==='wbgt'){if(v[f.key]<-112||v[f.key]>212)throw Error('Temperatures must be between −112 and 212 °F.');}else if(v[f.key]<0||(c.positive?.includes(f.key)&&v[f.key]===0))throw Error(f.label+' must be '+(c.positive?.includes(f.key)?'greater than zero.':'zero or greater.'));}if(v.strength>100)throw Error('Available chlorine cannot exceed 100%.');const result=c.calc(v);if(!Number.isFinite(result[0]))throw Error('Values are too large to calculate.');return result;}
export function flagCondition(value){if(!Number.isFinite(value))throw Error('Invalid WBGT.');const t=Number(value.toFixed(1));if(t<78)return{color:'gray',label:'Below flag range'};if(t<82)return{color:'white',label:'White flag'};if(t<85)return{color:'green',label:'Green flag'};if(t<88)return{color:'yellow',label:'Yellow flag'};if(t<90)return{color:'red',label:'Red flag'};return{color:'black',label:'Black flag'};}
function fmt(v){return new Intl.NumberFormat('en',{maximumSignificantDigits:5}).format(v);}
if(typeof document!=='undefined'){
const libraryToggle=document.getElementById('library-toggle');
libraryToggle.addEventListener('click',()=>{const library=document.getElementById('calculator-library');const collapsed=!library.hidden;library.hidden=collapsed;document.querySelector('.shell').classList.toggle('library-collapsed',collapsed);libraryToggle.setAttribute('aria-expanded',String(!collapsed));libraryToggle.textContent=(collapsed?'Show':'Hide')+' Calculator Library';});

let current,weatherControl,weatherResult,weatherMode=false;const byId=id=>document.getElementById(id);const nav=byId('navigation');let group='';for(const c of calculators){if(group!==c.group){group=c.group;const h=document.createElement('h2');h.textContent=group;nav.append(h);}const b=document.createElement('button');b.textContent=c.title;const arrow=document.createElement('span');arrow.textContent='↗';b.append(arrow);b.dataset.id=c.id;b.onclick=()=>select(c.id);nav.append(b);}
function renderResult(){const resultPanel=document.querySelector('.result-panel');delete resultPanel.dataset.flag;if(current.id==='wbgt'&&weatherMode&&!weatherResult){byId('result').textContent='Load station weather to calculate an estimated WBGT.';return;}const values=Object.fromEntries(new FormData(byId('fields')));if(current.id==='wbgt'&&weatherMode)Object.assign(values,{wet:weatherResult.wet*9/5+32,globe:weatherResult.globe*9/5+32,dry:weatherResult.air*9/5+32});const box=byId('result');box.replaceChildren();try{const [value,unit,detail]=calculate(current.id,values);const v=document.createElement('div');v.className='value';v.textContent=current.id==='wbgt'?value.toFixed(1):fmt(value);const u=document.createElement('span');u.className='unit';u.textContent=unit;v.append(u);const d=document.createElement('div');d.className='result-detail';d.textContent=detail+(current.id==='wbgt'&&weatherMode?' Estimated from '+weatherResult.station+' · observation '+new Date(weatherResult.time).toLocaleString()+'.':'');if(current.id==='wbgt'){const flag=flagCondition(value);resultPanel.dataset.flag=flag.color;const badge=document.createElement('div');badge.className='flag-status';badge.textContent='⚑ '+flag.label;box.append(badge);}box.append(v,d);if(current.id==='wbgt'){const legend=document.createElement('div');legend.className='flag-reference';legend.textContent='Flag bands (°F): below 78 gray · 78–81.9 white · 82–84.9 green · 85–87.9 yellow · 88–89.9 red · 90+ black. Condition follows the displayed one-decimal WBGT, matching the supplied reference. ';const link=document.createElement('a');link.href='https://www.jbsa.mil/News/News/Article/1160948/its-getting-hot-out-there-so-check-your-workrest-cycle/';link.textContent='Flag guidance';link.target='_blank';link.rel='noopener';legend.append(link);box.append(legend);}}catch(e){const error=document.createElement('div');error.className='error';box.append(error);}}
function select(id){weatherControl?.reset();current=calculators.find(c=>c.id===id)||calculators[0];for(const b of nav.querySelectorAll('button')){b.classList.toggle('active',b.dataset.id===current.id);b.setAttribute('aria-pressed',String(b.dataset.id===current.id));}for(const k of ['title','description','formula','notes'])byId(k).textContent=current[k];byId('category').textContent=current.group;byId('index').textContent='TOOL '+String(calculators.indexOf(current)+1).padStart(2,'0')+' / '+current.group.toUpperCase();byId('symbol').textContent=current.icon;byId('source').href=current.source;const form=byId('fields');form.replaceChildren();for(const f of current.fields){const label=document.createElement('label');label.textContent=f.label;const input=document.createElement(f.options?'select':'input');input.name=f.key;if(f.options){for(const [value,title] of f.options){const o=document.createElement('option');o.value=value;o.textContent=title;input.append(o);}}else{input.type='number';input.step='any';}input.value=current.id==='wbgt'&&!f.options?Number(f.value).toFixed(1):f.value;label.append(input);form.append(label);}const weatherPanel=byId('weather-panel');if(weatherPanel)weatherPanel.hidden=current.id!=='wbgt';renderResult();}
byId('fields').oninput=renderResult;byId('fields').onchange=renderResult;byId('fields').onsubmit=e=>e.preventDefault();byId('reset').onclick=()=>select(current.id);select('dose');
const weatherPanel=document.createElement('section');weatherPanel.id='weather-panel';weatherPanel.className='panel weather-panel';weatherPanel.hidden=true;document.querySelector('.workspace').before(weatherPanel);
weatherControl=mountAWOS(weatherPanel,r=>{weatherResult=r;for(const [key,value] of Object.entries({wet:(r.wet*9/5+32).toFixed(1),globe:(r.globe*9/5+32).toFixed(1),dry:(r.air*9/5+32).toFixed(1)})){byId('fields').elements.namedItem(key).value=value;}renderResult();},mode=>{weatherMode=mode;weatherResult=null;if(current?.id==='wbgt'){for(const f of current.fields){const input=byId('fields').elements.namedItem(f.key);if(!input)continue;input.readOnly=mode;input.value=mode?'':Number(f.value).toFixed(1);}renderResult();}});
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'calculate_toolbox_result',description:'Calculate radiation, chlorine or measured WBGT values and display the inputs and result in the toolbox.',inputSchema:{type:'object',properties:{calculator:{type:'string',enum:calculators.map(c=>c.id)},values:{type:'object',additionalProperties:{type:['number','string']}}},required:['calculator','values'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!input.values)throw Error('Calculator and values are required.');const result=calculate(input.calculator,input.values);select(input.calculator);for(const [key,value] of Object.entries(input.values)){const control=byId('fields').elements.namedItem(key);if(control)control.value=value;}renderResult();return{calculator:current.id,value:result[0],unit:result[1],detail:result[2]};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
}
